tinyMCE.addI18n('en.advanced',{
style_select:"Estilos",
font_size:"Tamanho da fonte",
fontdefault:"Fonte",
block:"Formato",
paragraph:"Paragraph",
div:"Div",
address:"Endereço",
pre:"Pré-formatado",
h1:"Heading 1",
h2:"Heading 2",
h3:"Heading 3",
h4:"Heading 4",
h5:"Heading 5",
h6:"Heading 6",
blockquote:"Blockquote",
code:"Code",
samp:"Exemplo de código",
dt:"Definição de termo ",
dd:"Definição da descrição",
bold_desc:"Negrito (Ctrl+B)",
italic_desc:"Itálico (Ctrl+I)",
underline_desc:"Sublinhado (Ctrl+U)",
striketrough_desc:"Strikethrough",
justifyleft_desc:"Alinhar à esquerda",
justifycenter_desc:"Centralizar",
justifyright_desc:"Alinhar à direita",
justifyfull_desc:"Justificar",
bullist_desc:"Lista não ordenada",
numlist_desc:"Lista ordenada",
outdent_desc:"Outdent",
indent_desc:"Indent",
undo_desc:"Desfazer (Ctrl+Z)",
redo_desc:"Refazer (Ctrl+Y)",
link_desc:"Inserir/Editar link",
unlink_desc:"Desabilitar link",
image_desc:"Inserir/editar imagem",
cleanup_desc:"Limpar código desarrumado",
code_desc:"Edit HTML Source",
sub_desc:"Subscript",
sup_desc:"Superscript",
hr_desc:"Inserir linha horizontal",
removeformat_desc:"Remover formatação",
custom1_desc:"Sua descrição aqui.",
forecolor_desc:"Selecionar cor do texto",
backcolor_desc:"Seleciona cor de fundo do texto",
charmap_desc:"Inserir caracter especial",
visualaid_desc:"Presilhas das linhas/elementos invisíveis",
anchor_desc:"Inserir/editar âncora",
cut_desc:"Recortar",
copy_desc:"Copiar",
paste_desc:"Colar",
image_props_desc:"Propriedades da imagem",
newdocument_desc:"Novo documento",
help_desc:"Ajuda",
blockquote_desc:"Parágrafo",
clipboard_msg:"Copiar/Recortar/Colar não está disponível no Mozila e Firefox.\r\nDeseja alguma informação extra sobre este incidente?",
path:".",
newdocument:"Tem certeza que deseja limpar todos conteúdo?",
toolbar_focus:"Ir para o botão de ferramenta - Alt+Q, Ir para o editor - Alt-Z, Ir para o caminho - Alt-X",
more_colors:"Mais cores"
});